Coordinate 1: (786, 762)
Coordinate 2: (1060, 818)
Coordinate 3: (556, 600)
Coordinate 4: (535, 664)
Coordinate 5: (1409, 665)
Coordinate 6: (1911, 230)
Coordinate 7: (1912, 394)
Coordinate 8: (535, 217)
Coordinate 9: (534, 916)
Coordinate 10: (1455, 971)
NotifyURL: http://miaotixing.com/trigger?id=tOOmTSO
